name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: "🦀 Build"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -r --verbose
    - name: Benchmark
      run: cargo run -r --verbose -- --run-all -b
    - name: Run tests
      run: cargo test --verbose

  update-results-file:
    needs: build
    if: github.ref == 'refs/heads/main'
    name: "🦀 Update Results"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run application
        run: cargo run -r -- --run-all -b > results.txt

      - name: Update Results.txt
        run: |
          git config user.name 'Alberto'
          git config user.email 'albgp22@users.noreply.github.com'
          git add results.txt
          git commit -m "Update results.txt"
          git push
