name: AoC main CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "29 2 * * 1"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: "🦀 Build"
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build -r --verbose
      - name: Benchmark
        run: cargo run -r --verbose -- --run-all -b
      - name: Run tests
        run: cargo test --verbose

  rust-clippy-analyze:
    needs: build
    name: "Run rust-clippy 🦀 analyzing"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy,rustfmt
          override: true

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

  update-results-file:
    needs: build
    if: github.ref == 'refs/heads/main'
    name: "🦀 Update Results"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run application
        run: cargo run -r -- --run-all -b > results.txt

      - name: Update Results.txt
        run: |
          git config user.name 'Alberto'
          git config user.email 'albgp22@users.noreply.github.com'
          git add results.txt
          git commit -m "Update results.txt"
          git push
