name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install nightly
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Build
      run: cargo build -r --verbose
    - name: Benchmark
      run: cargo run -r --verbose -- --run-all -b
    - name: Run tests
      run: cargo test --verbose
