
name: update-results-file

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  update-results-file:
    name: "Update Results"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run application
        run: cargo run -r -- --run-all -b > results.txt

      - name: Update Results.txt
        run: |
          git config user.name 'Alberto'
          git config user.email 'albgp22@users.noreply.github.com'
          git add results.txt
          git commit -m "Update results.txt"
          git push